general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
dynamic_padding = true

opacity = 1.0

[font]
size = 14.0

normal.family = "JetBrainsMono Nerd Font"

[keyboard]
bindings = [
# Open new windows at the same dir
{ key = "Enter", mods = "Command|Shift", action = "CreateNewWindow" },
# Scroll keybindings. Use mode = "~Alt" to disable keybinding in apps like nvim
{ key = "PageUp", mods = "None", action = "ScrollLineUp", mode = "~Alt" },
{ key = "PageDown", mods = "None", action = "ScrollLineDown", mode = "~Alt" },
{ key = "PageUp", mods = "Shift", action = "ScrollHalfPageUp", mode = "~Alt" },
{ key = "PageDown", mods = "Shift", action = "ScrollHalfPageDown", mode = "~Alt" },
{ key = "PageUp", mods = "Control|Shift", action = "ScrollPageUp", mode = "~Alt" },
{ key = "PageDown", mods = "Control|Shift", action = "ScrollPageDown", mode = "~Alt" },
]
